In [5]:
import numpy as np

#1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
# a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
# b. Find the indices of elements greater than 10 in the array.

# arr = np.array([1, 2, 3, 4, 5,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
arr = np.arange(1,21) # arange - it acts like range function of for loop 
print("sum is:",arr.sum())
print("mean is:",arr.mean())
print("median is:",np.median(arr))
print(f"S.D is {np.std(arr):.3f}")  # .3f for float value upto 3 decimal

indices = np.where(arr > 10)[0] # it shows all number after 10, where method is used for that
print("Indices of elements greater than 10:", indices)

sum is: 210
mean is: 10.5
median is: 10.5
S.D is 5.766
Indices of elements greater than 10: [10 11 12 13 14 15 16 17 18 19]


In [1]:
import numpy as np

#2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
# a. Print the array.  
# b. Find the transpose of the array.  
# c. Calculate the row-wise and column-wise sums of the array. 

arr = np.arange(1,17).reshape(4,4)
print("original array:\n",arr)

transpose = arr.T
print("transpose array:\n", transpose)

row = arr.sum(axis=1)
col = arr.sum(axis=0)

print("row wise sum:", row)
print("column wise sum: ", col)

original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
transpose array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
row wise sum: [10 26 42 58]
column wise sum:  [28 32 36 40]


In [3]:
import numpy as np

# 3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
# a. Perform element-wise addition, subtraction, and multiplication.  
# b. Compute the dot product of the two arrays.

arr1 = np.random.randint(1,21, size=(3,3)) # this will print random number betweeen 1 to 20 and then it will arrange it in size of 3*3 array
arr2 = np.random.randint(1,21, size=(3,3))

print(arr1,"\n--------\n", arr2)

print("addition:\n", arr1+arr2)
print("subtraction:\n", arr1-arr2)
print("multiplication:\n ", arr1*arr2)
print("dot product: \n", np.dot(arr1,arr2))


[[ 9  1 18]
 [12  4  4]
 [ 7  8  9]] 
--------
 [[ 4  7 14]
 [ 9 15 20]
 [ 7  4  1]]
addition:
 [[13  8 32]
 [21 19 24]
 [14 12 10]]
subtraction:
 [[  5  -6   4]
 [  3 -11 -16]
 [  0   4   8]]
multiplication:
  [[ 36   7 252]
 [108  60  80]
 [ 49  32   9]]
dot product: 
 [[171 150 164]
 [112 160 252]
 [163 205 267]]


In [4]:
import numpy as np

# 4. Reshape a 1D array of size 12 into a 3 X 4 2D array and 
# slice the first two rows and last two columns.

arr = np.arange(1,13).reshape(3,4)
print(arr)

sliced = arr[0:2, -2:]
print("sliced array:\n", sliced)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sliced array:
 [[3 4]
 [7 8]]
